name: Build Android AAB

defaults:
  run:
    working_directory: artifacts/pethub-mobile

jobs:
  build_android:
    name: Android production build
    type: build
    params:
      platform: android
      profile: production